# Generated by Django 4.2.2 on 2023-07-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('time_modified', 'date_created')},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('time_modified', 'date_created')},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time_created',
            new_name='time_modified',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='time_created',
            new_name='time_modified',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
