# Generated by Django 4.2.2 on 2023-07-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Tag',
        ),
    ]
