# Generated by Django 4.2.2 on 2023-07-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
