# Generated by Django 4.2.2 on 2023-07-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
