# Generated by Django 4.2.2 on 2023-07-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_user_options_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.message')),
            ],
            bases=('base.message',),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default=models.CharField(max_length=200, null=True), max_length=200, null=True),
        ),
    ]
