# Generated by Django 4.2.2 on 2023-07-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tweet_alter_user_display_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tweet',
        ),
    ]
