# Generated by Django 4.2.2 on 2023-07-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('time_modified', 'date_created')},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('time_modified', 'date_created')},
        ),
    ]
