# Generated by Django 4.2.2 on 2023-07-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_tweet_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
    ]
